import Providers from '@/components/Providers.server';
import type { Metadata } from 'next';
import '../../styles/globals.css';
import { hasLocale, Locale } from 'next-intl';
import { routing } from '@/lib/i18n/routing';
import { notFound } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: Readonly<LayoutProps<'/[locale]'>>) {
  const { locale } = await params as { locale: Locale }
  if (!hasLocale(routing.locales, locale)) return notFound()
  
  setRequestLocale(locale)

  const { language } = new Intl.Locale(locale)

  return (
    <html lang={language}>
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
